version: "2"

services:

# MySQL database container
  namegoeshere-db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpass
      MYSQL_DATABASE: namegoeshere
      MYSQL_USER: usergoeshere
      MYSQL_PASSWORD: passgoeshere
    container_name: namegoeshere-db

# wordpress container dependent on the db container
  namegoeshere-wp:
    depends_on:
      - namegoeshere-db
    volumes:
      - ./app:/var/www/html
    image: wordpress:latest
    expose:
      - 80
    ports:
      - 2222:2222
    restart: always
    environment:
      VIRTUAL_HOST: domaingoeshere
      LETSENCRYPT_HOST: domaingoeshere
      LETSENCRYPT_EMAIL: emailgoeshere
      WORDPRESS_DB_NAME: namegoeshere
      WORDPRESS_DB_HOST: namegoeshere-db
      WORDPRESS_DB_USER: usergoeshere
      WORDPRESS_DB_PASSWORD: passgoeshere
    container_name: namegoeshere

volumes:
    db_data:

networks:
  default:
    external:
      name: nginx-proxy