version: "2"

services:

# MySQL database container
  namegoeshere-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpass
      MYSQL_DATABASE: namegoeshere
      MYSQL_USER: usergoeshere
      MYSQL_PASSWORD: passgoeshere
    container_name: namegoeshere-db

# wordpress container dependent on the db container
  namegoeshere-app:
    depends_on:
      - namegoeshere-db
    volumes:
      - ./app:/var/www/html
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 80
    restart: always
    environment:
      VIRTUAL_HOST: domaingoeshere
      LETSENCRYPT_HOST: domaingoeshere
      LETSENCRYPT_EMAIL: emailgoeshere
    container_name: namegoeshere

volumes:
    db_data:

networks:
  default:
    external:
      name: nginx-proxy